### ISSUE TITLE
[2.5.12] The ingestion of messages fails during the Topics creation

### ISSUE THREAD

**Issue by maephisto666** [Backbase/bb-fuel#121]
I am using `bb-fuel` version 2.5.12 (for DBS 2.17.3). When ingesting the messages for Message Center, I get the error below

```
Request method:	POST
Request URI:	https://localhost/api/messages-presentation-service/v4/message-center/topics?_csrf=d81fd1c3-d91b-4234-8ab5-8c8e4f71f019
Proxy:			<none>
Request params:	<none>
Query params:	_csrf=d81fd1c3-d91b-4234-8ab5-8c8e4f71f019
Form params:	<none>
Path params:	<none>
Headers:		Accept=*/*
				Content-Type=application/json; charset=UTF-8
Cookies:		Authorization=eyJraWQiOiJNYmV1VmVVWlhVT2FJcDgwYmx1XC9sanFOQjNKZE9aSDgxQ3JGU0tpMmVcL2M9IiwiY3R5IjoiSldUIiwiZW5jIjoiQTEyOENCQy1IUzI1NiIsImFsZyI6ImRpciJ9..UBI7-aBKE0hWnWnTugATuw.BmTobQi7qdB58MFI0CJb4s_3R6kXKOenRpYOSEg18CbpWBw6podVqAjS-VrzDRQQQUcqzFEaXXihmWBLNI_mhizaZfKvLXyNkvYZTJqidp7j7jZnw6axME4LRV0j9XaEyaLYcIDGGQfoVY8FeS1X_qwkDeVLjaeBpYbvsRUUpV-u2bouMIPGnk5tcShA9KVMuNcveIUD1kVO4xTO6kGn2nG5nl2UFKkZNw2VkCCYnCvWDqxwmXYU5aM1aY6N81dujZFrHovYAeJwTzLP-gE23yJeU2VlMdlNy0KsZjcA0ubQ5tVDMqnC4zipSgptlPIsHbKBzCkhaubmW3lNbjIedOZjtrtY_694pQaJPFregYZa9NksLGp_eMbdOwcRFIBKgCVqyDpDLTHrILJhqDm6j_FDmGhgIQ_gbOqFhx7S1kpP4AocKWZfBLUPUBZcouFM7xvcD9Sd_fozIGX_jpJnuTWdkJTvQYqzJFkgAazSrPTZk5iDfetsd8Mo3t3mU3R1uVeIWpsh0044YEBWMWINOYI5zvw4vSz6r7XnIkVzHjYiutFzbTzZJSQZp1ggnEnGlgHruowX7nYQaWOdBc-nML7Sr1tXyEwHcTts0CO5ZOf9PqinGWnzJxuteJrMS3EL.Mn_rVy6IvEl4s3Io8fTZgQ
				XSRF-TOKEN=d81fd1c3-d91b-4234-8ab5-8c8e4f71f019
				USER_CONTEXT=eyJraWQiOiJaNXB5dkxcL3FMYUFyR3ZiTkY3Qm11UGVQU1Q4R0I5UHBPR0RvRnBlbmIxOD0iLCJjdHkiOiJKV1QiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..i7-kzN_QUBMjEKeSUN4FwA.aFJH_cLqSDMuIBqRa8-3RTCbXTOXwJA2uXsFKnWxokug5VO63rsTsgkwaiR8c6qQgztl6-6aAsWrEtPwdfOZpMPNRgLOaxF3eOyEKOvpsca-oSC6gwbXSQM88M5wQpeEwA1Uk73iSas4n5JUY2mYOsYkTXQuUWxXKPtDs8jqSqVa8_22NonpHZZjfLbsokfqyLPisltKNEgeOiVtCL1Asum1ZhOy1Oh3e0kKX6KuIn7dHPT62QiOdhTMfkRFE_XKhipVUtCh3HF9UJmduqQ0pvzurMmQ8JLP2C8SFvSPvPcsPEGl6Kp-UH9aEi2SySaS.J4kqVxk0Q8y1nLKASop4Ew
Multiparts:		<none>
Body:
{
    "name": "Odit saepe.",
    "subscribers": [
        "admin"
    ]
}

HTTP/1.1 400 
Server: nginx/1.17.8
Date: Mon, 04 May 2020 13:26:57 GMT
Content-Type: application/json;charset=UTF-8
Content-Length: 141
Connection: keep-alive
Set-Cookie: XSRF-TOKEN=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
Set-Cookie: XSRF-TOKEN=72a1d0cd-d032-404d-a9f3-04ecd91bdb20; Path=/
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

{
    "message": "Not all users were found.",
    "errors": [
        {
            "message": "Not all users were found.",
            "key": "user.get.error.message.ALL_USERS_NOT_FOUND"
        }
    ]
}
2020-05-04 15:26:57.819 ERROR [bb-fuel,,,] 78834 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.AssertionError: 1 expectation failed.
Expected status code <202> but was <400>.

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:483)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:655)
	at sun.reflect.GeneratedMethodAccessor300.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
	at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:123)
	at io.restassured.specification.ResponseSpecification$statusCode$2.callCurrent(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:131)
	at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:119)
	at com.backbase.ct.bbfuel.configurator.MessagesConfigurator.lambda$ingestConversations$0(MessagesConfigurator.java:58)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:559)
	at com.backbase.ct.bbfuel.configurator.MessagesConfigurator.ingestConversations(MessagesConfigurator.java:54)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.backbase.ct.bbfuel.setup.CapabilitiesDataSetup.ingestConversationsPerUser(CapabilitiesDataSetup.java:158)
	at com.backbase.ct.bbfuel.setup.CapabilitiesDataSetup.initiate(CapabilitiesDataSetup.java:66)
	at com.backbase.ct.bbfuel.Runner.ingestCapabilityData(Runner.java:101)
	at com.backbase.ct.bbfuel.Runner.ingestEnvironment(Runner.java:84)
	at com.backbase.ct.bbfuel.Runner.doIt(Runner.java:62)
	at com.backbase.ct.bbfuel.Runner.run(Runner.java:42)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:772)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:319)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	at com.backbase.ct.bbfuel.BbFuelApplication.main(BbFuelApplication.java:20)
```

The reason is that the api POST `/messages-presentation-service/v4/message-center/topics` can only accept a list of internal user ids, while bb-fuel is sending admin that is an external user id (specifically as subscriber of the topic).

I have a fix for it, using the `userPresentationRestClient` to translate the external user id into an internal user id. How can I be sure I follow the right process to submit the fix in the appropriate version bb-fuel?

**Comment by richard-blank** [comment]
your fix has been merged into `2.6.4` correlating to `DBS 2.18.0`
